### ISSUE TITLE
/cloudmesh/sql/hid-sp18-521

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-521#2]
path should be 

/cloudmesh/sql

**Comment by srsteinb** [comment]
Will update this path in all files to /cloudmesh/sql where it was /cloudmesh/sql/hid-sp18-521.

**Comment by srsteinb** [comment]
Changed API path from /cloudmesh/sql/hid-sp18-521 to /cloudmesh/sql.
